#!/bin/bash

echo "Run_VST with parameters $0 $1 $2 $3"

# intensity lost sensitivity is for fluorescence videos
# lost sensitivity is for brightfield videos


# arguments: initial_tracking_frame, first_frame, out_name

# Set Parameters to be used for tracking and autofind
export r=12
export precision=0.02
export sample_spacing=0.5
export border_zone=3
export tracker_zone=5

# Autofind for brightfield beads
export maintain=0
export threshold=0
export window=10
export lost_sens=0

# Autofind for fluorescent beads
export blur_lost_and_found=2
export center_surround=2
export maintain_fluorescent=25
export fluorescent_spot_threshold=0.52
export fluorescent_max_regions=400
export intens_lost_sens=0.5

# Set return value to 254(-2 in C code)
export RET=254

echo "Finding beads in first video ($1)..."
while [ $RET -eq 254 ]
do
  /afs/cs.unc.edu/home/cshao/compression_project/video2/video_build/video_spot_tracker_nogui -nogui -radius $r -precision $precision -sample_spacing $sample_spacing -dead_zone_around_border $border_zone -dead_zone_around_trackers $tracker_zone -maintain_this_many_beads $maintain -candidate_spot_threshold $threshold -sliding_window_radius $window -maintain_fluorescent_beads $maintain_fluorescent -fluorescent_spot_threshold $fluorescent_spot_threshold -fluorescent_max_regions $fluorescent_max_regions -blur_lost_and_found $blur_lost_and_found -center_surround $center_surround -lost_behavior 1 -intensity_lost_sensitivity $intens_lost_sens -lost_tracking_sensitivity $lost_sens -tracker 0 0 $r -outfile "$3"lottanerve_tmp "$1"
  let "RET=$?"
done

echo "Tracking resulting beads in second video ($2)..."
export r=12
export precision=0.02
export sample_spacing=0.5
export border_zone=3
export tracker_zone=5
#export threshold=0.8 
export window=10
export intens_lost_sens=0.5

# Brightfield lost tracking sensitivity
export lost_sens=0


# old call to video_spot_tracker for tracking beads in Brightfield based on parameters:  still have no way to decide which tracking modality we need to use.  Monoptes has brightfield and fluorescence capability, Panoptes has only fluorescence
#./video_spot_tracker_nogui -nogui -log_video 300 -lost_behavior 1 -precision $precision -sample_spacing $sample_spacing -dead_zone_around_border $border_zone -dead_zone_around_trackers $tracker_zone -lost_tracking_sensitivity $lost_sens -tracker 0 0 $r -continue_from "$3"lottanerve_tmp.csv -outfile "$3" "$2"

# set up for fluorescence in Panoptes
/afs/cs.unc.edu/home/cshao/compression_project/video2/video_build/video_spot_tracker_nogui -nogui -log_video 300 -lost_behavior 1 -precision $precision -sample_spacing $sample_spacing -dead_zone_around_border $border_zone -dead_zone_around_trackers $tracker_zone -blur_lost_and_found $blur_lost_and_found -center_surround $center_surround -lost_tracking_sensitivity $lost_sens -tracker 0 0 $r -continue_from "$3"lottanerve_tmp.csv -outfile "$3" "$2"

# Delete temporary files 
#rm -f "$3"lottanerve_tmp.csv
#rm -f "$3"lottanerve_tmp.vrpn

echo "Done tracking!"

